apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot-frontend
  namespace: group-4-dev
secrets:
  - name: containerreg-pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-frontend
  namespace: group-4-dev
rules:
  - resources:
      - deployments
    apiGroups:
      - apps
    verbs:
      - get
      - create
      - list
      - patch
      - watch
  - resources:
      - routes
    apiGroups:
      - route.openshift.io
    verbs:
      - get
      - create
      - patch
  - resources:
      - services
    apiGroups:
      - ""
    verbs:
      - get
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-frontend
  namespace: group-4-dev
roleRef:
  name: deployer
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: build-robot
    kind: ServiceAccount