apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-4-frontend
  labels:
    app: group-4-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-4-frontend
  template:
    metadata:
      labels:
        app: group-4-frontend
    spec:
      securityContext:
          runAsGroup: 1000
      containers:
      - name: react-app
        image: quay.io/cayops/group-4-frontend:2f5b6ae2f5f9e0f3a1408b1c4c809fd53d3e8a71
        ports:
        - containerPort: 3000