apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-4-app
  labels:
    app: group-4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-4-app
  template:
    metadata:
      labels:
        app: group-4-app
    spec:
      containers:
      - name: react-app
        image: quay.io/cayops/group-4-frontend:latest
        ports:
        - containerPort: 3000