apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-4-frontend
  labels:
    app: group-4-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-4-frontend
  template:
    metadata:
      labels:
        app: group-4-frontend
    spec:
      securityContext:
          runAsGroup: 1000
      containers:
      - name: react-app
        image: quay.io/cayops/group-4-frontend:a3f5616551484024e53b6972ccf221e36da35198
        ports:
        - containerPort: 3000